### PR TITLE
feat: adds dependabot

### PR DESCRIPTION
**Pull request by timvancleef**
# Pull Request Template

## Description

This PR adds [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically) to the project which keeps track of dependency updates and will create PRs for each outdated dependency. Currently it is configured to check for npm updates weekly.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

No special testing was done. I checked on my fork that the PRs are created once i added dependabot 🙂 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by cremich** [comment]
Hi @timvancleef 
Thank you. This is really helpful. Was it by intention that some cdk libs are also updated to version 1.99.0 and some not?

**Comment by cremich** [comment]
Should we upgrade to cdk 1.99.0 for all libs?

**Comment by timvancleef** [comment]
> Hi @timvancleef
> Thank you. This is really helpful. Was it by intention that some cdk libs are also updated to version 1.99.0 and some not?

Whoops... didn't mean to also merge to the package udpates.
Just wanted to introduce dependabot, so that it can create the PR in this repo and we can decide what to update.
Will revert the changes to `package.json` and `package-lock.json`

**Review by cremich — APPROVED** [review]

**Comment by timvancleef** [comment]
> Hi @timvancleef
> Thank you. This is really helpful. Was it by intention that some cdk libs are also updated to version 1.99.0 and some not?

Dependabot by default will create only five PRs with dependency updates (https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#open-pull-requests-limit).
So this is why some of the dependencies are not updated.

Maybe for the start we could set it to 10?

**Comment by cremich** [comment]
Yeah makes sense so increase the limit so that we cover all current deps. We could have an eye in this as soon as we add new libraries 

Is it feasible to also create one consolidated PR instead of one per lib?

**Comment by cremich** [comment]
Seems not to be the case. But I found this here:

https://www.hrvey.com/blog/combine-dependabot-prs

**Comment by timvancleef** [comment]
Nice 🙂 
I will take a look at it.

**Pull request merged**
