### PR TITLE
Bump cdk version to 1.100.0

### PR DESCRIPTION
**Pull request by cremich**
## Description

Update CDK to version 1.100.0

### CODE REVIEW

**Comment by cremich** [comment]
Build failed but this is very strange. Can not reproduce this on my local machine.

**Comment by cremich** [comment]
@Bakkenrak @timvancleef any ideas why the build still fails in the github workflow? I also recreated the package-lock.json to be sure that all changes are in there.

**Comment by cremich** [comment]
Maybe I found a hint: https://github.com/aws/aws-cdk/issues/13743

Seems to be a problem with lockfile differences between npm version 6 and 7. I use 7 locally. Will investigate.

**Comment by cremich** [comment]
That was the issue. Build step succeeded. #hooray

**Review by Bakkenrak — APPROVED** [review]

**Comment by timvancleef** [comment]
> That was the root cause. Build step succeeded. #hooray

So that means we should stick to node 14 and npm 6?

**Review by timvancleef — APPROVED** [review]

**Comment by cremich** [comment]
@timvancleef that is right. Either this or update the used versions in the github workflow. 

Would be good to have a hint in the README about the used node and npm version. NPM 6 is default in node 14. Node 15 will use npm 7 by default.

**Comment by Bakkenrak** [comment]
I'd vote for version 14 over 15 as it's the LTS one. However, it would be easy to have the workflow run with both. Just need to extend the node version matrix.

**Comment by cremich** [comment]
+1 for node 14 as it is also the current lambda runtime version.

**Pull request merged**
